version: ~> 1.0

language: scala

scala:
  - 2.12.10
  - 2.13.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile

jdk:
  - openjdk8
  - openjdk11

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
