language: scala

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
  - 2.13.0

script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile

# Container-based build environment with faster boot times
sudo: false

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
