name: sbt

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [ '2.10.7', '2.11.12', '2.12.10', '2.13.1' ]
        java: [ '8', '11' ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - run: sbt ++${{ matrix.scala }} test:compile
